// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vklwmwlbgkvcevvihkrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbHdtd2xiZ2t2Y2V2dmloa3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTU4ODAsImV4cCI6MjA2MTY5MTg4MH0.lnREMrm0NaI6ug70Uw4Hz_cCd7w13p8GZvFSE1G6YnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);